### ISSUE TITLE
UI Elements - Typography

### ISSUE THREAD

**Issue by devjin0617** [devjin0617/vue2-admin-lte#16]
### talks
- [x] Headlines
- [x] Text Emphasis
- [x] Block Quotes
- [x] Block Quotes Pulled Right
- [x] Unordered List
- [x] Ordered Lists
- [x] Unstyled List
- [x] Description
- [x] Description Horizontal

@jinseongho 업무 할당 😄

**Comment by ChangJoo-Park** [comment]
성호님이 해주시는건가요

**Comment by devjin0617** [comment]
넵 😄 노가다 자신있다고 맡겨만 달라고 했습니다

**Comment by ChangJoo-Park** [comment]
든든하네요 assign 드리려고 했는데 아쉽게도 없네요  ㅋㅋㅋ

**Comment by devjin0617** [comment]
@jinseongho assign 지정 완료입니다 😄

**Comment by jinseongho** [comment]
이야

**Comment by devjin0617** [comment]
보고 따라해야할 사이트 링크 공유합니다.

https://almsaeedstudio.com/themes/AdminLTE/pages/UI/general.html

여기에서 하단 `Typography`쪽을 보면 됩니다

**Comment by devjin0617** [comment]
이건 제가 가져가겠습니다 😄

**Comment by devjin0617** [comment]
Typography 완료
