### ISSUE TITLE
Execute Template

### ISSUE THREAD

**Issue by ARCHAMO** [devjin0617/vue2-admin-lte#30]
Good morning. I am trying to clone the project but it does not show the template as I expect. This is a document that I did step by step from what I am doing.

I appreciate your help.

[Execute Template Error.docx](https://github.com/devjin0617/vue2-admin-lte/files/887613/Execute.Template.Error.docx)

**Comment by devjin0617** [comment]
Hello!
Just do not install vue2-admin-lte npm to see the demo.

What you tried is a mockup server (http://localhost:3000)
once again connect url to http://localhost:8080

1. download of clone to project of vue2-admin-lte
2. move the project directory
3. npm install ( i need npm version > 3 )
4. npm run dev ( wait for seconds )
5. open your browser and connect url (http://localhost:8080)

**Comment by ARCHAMO** [comment]
Goodnight.

Perform the steps that you comment and here I send you the results. I thank you for your help I could not see the template in operation.

Thank you

[Prueba Admin LTE.docx](https://github.com/devjin0617/vue2-admin-lte/files/888159/Prueba.Admin.LTE.docx)

**Comment by devjin0617** [comment]
```bash
vue2-admin-lte-master$ node build/dev-server.js
```
Please do it

**Comment by ChangJoo-Park** [comment]
@ARCHAMO, 
You should `git pull` vue2-admin-lte.
In windows environment, can't execute multiple npm scripts at once.
So, I add [npm-run-all](https://www.npmjs.com/package/npm-run-all) in this project and split dev script into mock and dev-server. If you run only mock or dev-server, you should run `npm run mock` or `npm run dev-server` .
If want run servers(mock and dev-server) at the same time, you should run `npm run dev` (same as before)

**Comment by ARCHAMO** [comment]
Thank you very much now if the template I could see complete. Although it lacks components such as datatables and Forms. But this is excellent. Thank you

**Comment by ChangJoo-Park** [comment]
@ARCHAMO

datatables and forms are under development. :)
