### ISSUE TITLE
Va-small-box custom link action

### ISSUE THREAD

**Issue by sbenitezma** [devjin0617/vue2-admin-lte#39]
Hello!
I've detected on component va-small-box:
`<div class="small-box" :class="bgColor">`
` <div class="inner">`
      `<h3>{{title}}</h3>`
`      <p>{{description}}</p>`
`    </div>`
`    <div class="icon">`
`      <i class="ion" :class="icon"></i>`
`    </div>`
`    <a href="#"  class="small-box-footer">{{moreText}} <i class="fa fa-arrow-circle-right"></i></a>`
`  </div>`
I cannot set custom vuejs function as action on click (like @click, v-on:click('customFunction')) on <a href=# to prevent link to # 
There's any way to change that? if there's any I appreciate to know that, else I will develop one and make pull request because I need it for my project :smile: 

Regards and thanks!

**Comment by devjin0617** [comment]
Thank you 😄

Add click event in SmallBox Component !

```
<template>
...
  <va-small-box @more-click="onMore"></va-small-box>
...
</template>

<script>
export default {
...
  methods: {
    onMore () {
         // here more event code
    }
  }
...
}
</script>
```

**Comment by tutkun** [comment]
it's usefull may be:

```php
<a
     href="javascript:;"
     class="small-box-footer"
>
     {{moreText}} <i class="fa fa-arrow-circle-right"></i>
</a>
```

**Comment by devjin0617** [comment]
Clsoed 😄

**Comment by sbenitezma** [comment]
Thanks! :smile:
