### ISSUE TITLE
Can't load va script

### ISSUE THREAD

**Issue by gadaica3** [devjin0617/vue2-admin-lte#44]
Hi all,

I'm now with vue.
I setup the app using this library for UI.
But when I import it:

`
import 'va/lib/css'
`
`
import 'va/lib/script'
`

It throws out:
`in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/renderer/App.vue
Module not found: Error: Can't resolve 'va/lib/css' in '/Applications/XAMPP/xamppfiles/htdocs/blogging/j14blog/src/renderer'
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/renderer/App.vue 2:0-20
 @ ./src/renderer/App.vue
 @ ./src/renderer/main.js
 @ multi ./.electron-vue/dev-client ./src/renderer/main.js`

Can you healp me please!
Thanks!
Ga

**Comment by gadaica3** [comment]
Please help @devjin0617

**Comment by hersonpc** [comment]
@gadaica3, Do you config webpack alias?

```
module.exports = {  
  resolve: {
    alias: {
      'va': 'vue2-admin-lte/src'
    }
  }
}
```

**Comment by devjin0617** [comment]
Closed
