### ISSUE TITLE
Can't npm run dev?

### ISSUE THREAD

**Issue by smarttang** [devjin0617/vue2-admin-lte#70]
ERROR  Failed to compile with 1 errors                                                                                                                                                                                      下午6:48:36

Module build failed: Error: Cannot find module 'eslint/lib/formatters/stylish'
Require stack:
- /Users/smarttang/Desktop/vue2-admin-lte/node_modules/eslint-loader/index.js
- /Users/smarttang/Desktop/vue2-admin-lte/node_modules/loader-runner/lib/loadLoader.js
- /Users/smarttang/Desktop/vue2-admin-lte/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/smarttang/Desktop/vue2-admin-lte/node_modules/webpack/lib/NormalModule.js
- /Users/smarttang/Desktop/vue2-admin-lte/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/smarttang/Desktop/vue2-admin-lte/node_modules/webpack/lib/Compiler.js
- /Users/smarttang/Desktop/vue2-admin-lte/node_modules/webpack/lib/webpack.js
- /Users/smarttang/Desktop/vue2-admin-lte/build/dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:954:17)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.module.exports (/Users/smarttang/Desktop/vue2-admin-lte/node_modules/eslint-loader/index.js:156:18)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
> Listening at http://localhost:8080

**Comment by relesssar** [comment]
me too

```
$ npm install

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: vue2-admin-lte@0.4.4
npm ERR! Found: sinon@1.17.7
npm ERR! node_modules/sinon
npm ERR!   dev sinon@"^1.17.7" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer sinon@">=2.1.0 <5" from karma-sinon-chai@1.3.4
npm ERR! node_modules/karma-sinon-chai
npm ERR!   dev karma-sinon-chai@"^1.2.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home//.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home//.npm/_logs/2021-04-22T03_46_09_826Z-debug.log


$ npm install --legacy-peer-deps
```
