### ISSUE TITLE
Font Awesome, Glyphicons NPM으로 진행하기

### ISSUE THREAD

**Issue by ChangJoo-Park** [devjin0617/vue2-admin-lte#9]

**Comment by ChangJoo-Park** [comment]
Font Awesome 추가했습니다
https://github.com/devjin0617/vue2-admin-lte/commit/6f4e614639905cef690644f3494f9f41209f68f7

**Comment by ChangJoo-Park** [comment]
Glyphicons 이거 혹시 많이 쓰나요?

**Comment by devjin0617** [comment]
AdminLTE에서는 아이콘들에서 좀 쓰는 것 같더라구요

**Comment by ChangJoo-Park** [comment]
Bootstrap 추가하니까 Glyphicon 자동으로 추가되네요 닫을게요

**Comment by devjin0617** [comment]
우왕! 몰랐네요! 감사합니다 😀
